apiVersion: v1
kind: ConfigMap
metadata:
  name: storefront-bff-config
  namespace: yas-dev
  labels:
    app: storefront-bff
data:
  SPRING_PROFILES_ACTIVE: custom
  SPRING_APPLICATION_JSON: |
    {
      "spring": {
        "cloud": {
          "gateway": {
            "server": {
              "webflux": {
                "default-filters": ["SaveSession"],
                "routes": [
                  {
                    "id": "product_api",
                    "uri": "http://product",
                    "predicates": ["Path=/api/product/**"],
                    "filters": ["RewritePath=/api/(?<segment>.*), /${segment}"]
                  },
                  {
                    "id": "cart_api",
                    "uri": "http://cart",
                    "predicates": ["Path=/api/cart/**"],
                    "filters": ["RewritePath=/api/(?<segment>.*), /${segment}", "TokenRelay="]
                  },
                  {
                    "id": "customer_api",
                    "uri": "http://customer",
                    "predicates": ["Path=/api/customer/**"],
                    "filters": ["RewritePath=/api/(?<segment>.*), /${segment}", "TokenRelay="]
                  },
                  {
                    "id": "order_api",
                    "uri": "http://order",
                    "predicates": ["Path=/api/order/**"],
                    "filters": ["RewritePath=/api/(?<segment>.*), /${segment}", "TokenRelay="]
                  },
                  {
                    "id": "tax_api",
                    "uri": "http://tax",
                    "predicates": ["Path=/api/tax/**"],
                    "filters": ["RewritePath=/api/(?<segment>.*), /${segment}"]
                  },
                  {
                    "id": "inventory_api",
                    "uri": "http://inventory",
                    "predicates": ["Path=/api/inventory/**"],
                    "filters": ["RewritePath=/api/(?<segment>.*), /${segment}", "TokenRelay="]
                  },
                  {
                    "id": "media_api",
                    "uri": "http://media",
                    "predicates": ["Path=/api/media/**"],
                    "filters": ["RewritePath=/api/(?<segment>.*), /${segment}"]
                  },
                  {
                    "id": "search_api",
                    "uri": "http://search",
                    "predicates": ["Path=/api/search/**"],
                    "filters": ["RewritePath=/api/(?<segment>.*), /${segment}"]
                  },
                  {
                    "id": "sampledata_api",
                    "uri": "http://sampledata",
                    "predicates": ["Path=/api/sampledata/**"],
                    "filters": ["RewritePath=/api/(?<segment>.*), /${segment}"]
                  },
                  {
                    "id": "ui",
                    "uri": "http://storefront-ui:3000",
                    "predicates": ["Path=/**"]
                  }
                ]
              }
            }
          }
        }
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backoffice-bff-config
  namespace: yas-dev
  labels:
    app: backoffice-bff
data:
  SPRING_PROFILES_ACTIVE: custom
  SPRING_APPLICATION_JSON: |
    {
      "spring": {
        "cloud": {
          "gateway": {
            "server": {
              "webflux": {
                "default-filters": ["SaveSession"],
                "routes": [
                  {
                    "id": "product_api",
                    "uri": "http://product",
                    "predicates": ["Path=/api/product/**"],
                    "filters": ["RewritePath=/api/(?<segment>.*), /${segment}", "TokenRelay="]
                  },
                  {
                    "id": "customer_api",
                    "uri": "http://customer",
                    "predicates": ["Path=/api/customer/**"],
                    "filters": ["RewritePath=/api/(?<segment>.*), /${segment}", "TokenRelay="]
                  },
                  {
                    "id": "order_api",
                    "uri": "http://order",
                    "predicates": ["Path=/api/order/**"],
                    "filters": ["RewritePath=/api/(?<segment>.*), /${segment}", "TokenRelay="]
                  },
                  {
                    "id": "tax_api",
                    "uri": "http://tax",
                    "predicates": ["Path=/api/tax/**"],
                    "filters": ["RewritePath=/api/(?<segment>.*), /${segment}", "TokenRelay="]
                  },
                  {
                    "id": "inventory_api",
                    "uri": "http://inventory",
                    "predicates": ["Path=/api/inventory/**"],
                    "filters": ["RewritePath=/api/(?<segment>.*), /${segment}", "TokenRelay="]
                  },
                  {
                    "id": "media_api",
                    "uri": "http://media",
                    "predicates": ["Path=/api/media/**"],
                    "filters": ["RewritePath=/api/(?<segment>.*), /${segment}", "TokenRelay="]
                  },
                  {
                    "id": "search_api",
                    "uri": "http://search",
                    "predicates": ["Path=/api/search/**"],
                    "filters": ["RewritePath=/api/(?<segment>.*), /${segment}", "TokenRelay="]
                  },
                  {
                    "id": "ui",
                    "uri": "http://backoffice-ui:3000",
                    "predicates": ["Path=/**"]
                  }
                ]
              }
            }
          }
        }
      }
    }
